export const LOGIN_USER_REQUEST_START = 'LOGIN_USER_REQUEST_START';
export const LOGIN_USER_REQUEST_SUCCESS = 'LOGIN_USER_REQUEST_SUCCESS';
export const LOGOUT_USER_REDIRECT = 'LOGOUT_USER_REDIRECT';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
