export const LIST_EMPLOYEES = 'LIST_EMPLOYEES';
export const LIST_EMPLOYEES_SUCCESS = 'LIST_EMPLOYEES_SUCCESS';
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
